mdapioutput/objects/Invoice__c.object
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>I-{0000}</displayFormat>
        <label>Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Price_before_tax__c</fullName>
        <label>Price (before tax)</label>
        <precision>8</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>CA</fullName>
                </value>
                <value>
                    <fullName>ID</fullName>
                </value>
                <value>
                    <fullName>OR</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

mdapioutput/objects/State_Sales_Tax__mdt.object
<CustomObject>
    <label>State Sales Tax</label>
    <pluralLabel>State Sales Taxes</pluralLabel>
    <fields>
        <fullName>Tax_Rate__c</fullName>
        <label>Tax Rate</label>
        <precision>6</precision>
        <required>true</required>
        <scale>4</scale>
        <type>Number</type>
    </fields>
</CustomObject>

mdapioutput/classes/InvoiceController.cls
public class InvoiceController {
    public List<InvoiceWrapper> invoices {get;set;}
    public InvoiceController() { 
        invoices = new List<InvoiceWrapper>();
        for (Invoice__c i : [SELECT ID, Name, State__c, Price_before_tax__c FROM Invoice__c]) { //query for the details of the records you want to display
            invoices.add(new InvoiceWrapper(i)); //add the invoice
        }
    }


    public class InvoiceWrapper {
        public Invoice__c invoice {get;set;}
        public Decimal afterTaxPrice {get;set;}
        
        public InvoiceWrapper(Invoice__c i) {
                this.invoice = i; //assign Invoice
                String state = invoice.State__c;
                
                State_Sales_Tax__mdt taxRate = [SELECT DeveloperName, Tax_Rate__c FROM State_Sales_Tax__mdt WHERE DeveloperName = :state];
                
                this.afterTaxPrice = (taxRate.Tax_Rate__c + 1) * i.Price_before_tax__c; // calculate after tax price
            }
    }
}